version: '3'

services:
  mongo:
    image: mongo
    restart: 'always'
    container_name: "eadapi-mongo"
    volumes: 
      - ./.dbcache/mongo/data:/data/db
    ports:
      - "27017:27017"
    networks:
      - backend 
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  api:
    image: node:12.19-slim
    container_name: "eadapi-api"
    ports:
      - "5000:5000"
    working_dir: "/home/node/app"
    volumes:
      - ./:/home/node/app
    command: "npm start"
    networks:
      - backend 

networks:
  backend:
    driver: "bridge"
